trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @antora/cli@2.0 -g @antora/site-generator-default@2.0 gh-pages@2.0.1
    git config user.email "kamesh.sampath@hotmail.com"
    git config user.name "kameshsampath"
    mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
    chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
  displayName: 'Install Tools and Packages'

- script: |
    antora --pull --stacktrace site.yml
  displayName: 'Generate Site'

- script: |
    gh-pages --dotfiles --message "Publishing new documentation **NO_CI**" --dist gh-pages
  displayName: 'Deploy Site'
